--------------------------------------------------------
--  Constraints for Table BRAND
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."BRAND" MODIFY ("BRAND_NAME" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."BRAND" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."BRAND" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."BRAND" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."BRAND" ADD PRIMARY KEY ("BRAND_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."CART" MODIFY ("CART_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."CART" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."CART" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."CART" ADD CONSTRAINT "CK_CART_TOTAL_PRICE" CHECK (TOTAL_PRICE >= 0) ENABLE;
  ALTER TABLE "OHOUSE"."CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY ("CART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "OHOUSE"."CART" ADD CONSTRAINT "UK_CART_MEMBER" UNIQUE ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART_ITEMS
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."CART_ITEMS" MODIFY ("CART_ITEMS_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."CART_ITEMS" MODIFY ("PRODUCT_OPTION_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."CART_ITEMS" MODIFY ("CART_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."CART_ITEMS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."CART_ITEMS" ADD CONSTRAINT "CK_CART_ITEMS_QUANTITY" CHECK (QUANTITY > 0) ENABLE;
  ALTER TABLE "OHOUSE"."CART_ITEMS" ADD CONSTRAINT "PK_CART_ITEMS" PRIMARY KEY ("CART_ITEMS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "OHOUSE"."CART_ITEMS" ADD CONSTRAINT "UK_CART_ITEMS_OPTION" UNIQUE ("CART_ID", "PRODUCT_OPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."CATEGORY" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."CATEGORY" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."CATEGORY" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COUPON
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."COUPON" MODIFY ("COUPON_NAME" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."COUPON" MODIFY ("DISCOUNT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."COUPON" MODIFY ("DISCOUNT_VALUE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."COUPON" MODIFY ("MIN_ORDER_PRICE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."COUPON" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."COUPON" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."COUPON" ADD CONSTRAINT "CK_COUPON_DISCOUNT_TYPE" CHECK (DISCOUNT_TYPE IN ('RATE', 'AMOUNT')) ENABLE;
  ALTER TABLE "OHOUSE"."COUPON" ADD CONSTRAINT "CK_COUPON_DISCOUNT_VALUE" CHECK (DISCOUNT_VALUE > 0) ENABLE;
  ALTER TABLE "OHOUSE"."COUPON" ADD CONSTRAINT "CK_COUPON_DATE" CHECK (START_DATE <= END_DATE) ENABLE;
  ALTER TABLE "OHOUSE"."COUPON" ADD PRIMARY KEY ("COUPON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DISCOUNT
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."DISCOUNT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."DISCOUNT" MODIFY ("DISCOUNT_RATE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."DISCOUNT" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."DISCOUNT" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."DISCOUNT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."DISCOUNT" ADD CONSTRAINT "CK_DISCOUNT_RATE" CHECK (DISCOUNT_RATE >= 0 AND DISCOUNT_RATE <= 100) ENABLE;
  ALTER TABLE "OHOUSE"."DISCOUNT" ADD CONSTRAINT "CK_DISCOUNT_DATE" CHECK (END_DATE >= START_DATE) ENABLE;
  ALTER TABLE "OHOUSE"."DISCOUNT" ADD PRIMARY KEY ("DISCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."MEMBER" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "OHOUSE"."MEMBER" ADD CONSTRAINT "UK_MEMBER_ID" UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER_COUPON
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."MEMBER_COUPON" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."MEMBER_COUPON" MODIFY ("COUPON_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."MEMBER_COUPON" MODIFY ("ISSUED_DATE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."MEMBER_COUPON" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."MEMBER_COUPON" ADD CONSTRAINT "CK_MEMBER_COUPON_STATUS" CHECK (STATUS IN ('AVAILABLE', 'USED', 'EXPIRED')) ENABLE;
  ALTER TABLE "OHOUSE"."MEMBER_COUPON" ADD PRIMARY KEY ("MEMBER_COUPON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OPTION_GROUP
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."OPTION_GROUP" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."OPTION_GROUP" MODIFY ("GROUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."OPTION_GROUP" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."OPTION_GROUP" ADD PRIMARY KEY ("OPTION_GROUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "OHOUSE"."OPTION_GROUP" ADD CONSTRAINT "UK_OPTION_GROUP" UNIQUE ("PRODUCT_ID", "GROUP_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "OHOUSE"."OPTION_GROUP" ADD CONSTRAINT "CK_OPTION_GROUP_REQUIRED" CHECK (REQUIRED IN ('0', '1')) ENABLE;
--------------------------------------------------------
--  Constraints for Table OPTION_VALUE
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."OPTION_VALUE" MODIFY ("OPTION_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."OPTION_VALUE" MODIFY ("OPTION_NAME" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."OPTION_VALUE" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."OPTION_VALUE" ADD PRIMARY KEY ("OPTION_VALUE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "OHOUSE"."OPTION_VALUE" ADD CONSTRAINT "UK_OPTION_VALUE" UNIQUE ("OPTION_GROUP_ID", "OPTION_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."ORDERS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."ORDERS" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."ORDERS" MODIFY ("COUPON_DISCOUNT" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."ORDERS" MODIFY ("DELIVERY_FEE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."ORDERS" MODIFY ("PAYMENT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."ORDERS" MODIFY ("ORDER_STATUS" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."ORDERS" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."ORDERS" ADD CONSTRAINT "CK_ORDER_STATUS" CHECK (ORDER_STATUS IN ('ORDERED', 'PAID', 'SHIPPING', 'DELIVERED', 'CANCEL', 'REFUND')) ENABLE;
  ALTER TABLE "OHOUSE"."ORDERS" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS_DETAIL
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."ORDERS_DETAIL" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."ORDERS_DETAIL" MODIFY ("PRODUCT_OPTION_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."ORDERS_DETAIL" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."ORDERS_DETAIL" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."ORDERS_DETAIL" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."ORDERS_DETAIL" ADD CONSTRAINT "CK_ORDER_DETAIL_PRICE" CHECK (PRICE >= 0) ENABLE;
  ALTER TABLE "OHOUSE"."ORDERS_DETAIL" ADD CONSTRAINT "CK_ORDER_DETAIL_QUANTITY" CHECK (QUANTITY > 0) ENABLE;
  ALTER TABLE "OHOUSE"."ORDERS_DETAIL" ADD PRIMARY KEY ("ORDER_DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."PRODUCT" MODIFY ("BRAND_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT" MODIFY ("UPDATED" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT" ADD PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_IMAGE
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."PRODUCT_IMAGE" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT_IMAGE" MODIFY ("IMAGE_URL" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT_IMAGE" MODIFY ("IMAGE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT_IMAGE" MODIFY ("SORT_ORDER" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT_IMAGE" ADD PRIMARY KEY ("IMAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_OPTION
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."PRODUCT_OPTION" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT_OPTION" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT_OPTION" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT_OPTION" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT_OPTION" ADD PRIMARY KEY ("PRODUCT_OPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "OHOUSE"."PRODUCT_OPTION" ADD CONSTRAINT "UK_PRODUCT_OPTION_SKU" UNIQUE ("SKU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_OPTION_VALUE
--------------------------------------------------------

  ALTER TABLE "OHOUSE"."PRODUCT_OPTION_VALUE" MODIFY ("PRODUCT_OPTION_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT_OPTION_VALUE" MODIFY ("OPTION_VALUE_ID" NOT NULL ENABLE);
  ALTER TABLE "OHOUSE"."PRODUCT_OPTION_VALUE" ADD CONSTRAINT "PK_PRODUCT_OPTION_VALUE" PRIMARY KEY ("PRODUCT_OPTION_VALUE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
