/idcheck.ajax=com.ohouse.member.handler.IdCheckHandler
/namecheck.ajax=com.ohouse.member.handler.NameCheckHandler
/brandnamecheck.ajax=com.ohouse.seller.handler.BrandNameCheckHandler
/businessnumbercheck.ajax=com.ohouse.seller.handler.BusinessNumberCheckHandler
/mailordernumbercheck.ajax=com.ohouse.seller.handler.MailOrderNumberCheckHandler
/emailcheck.ajax=com.ohouse.seller.handler.EmailCheckHandler
/search/topKeywords.ajax=com.ohouse.search.handler.TopKeywordHandler
/checkCurrentPwd.ajax=com.ohouse.member.handler.CheckCurrentPwdHandler