/main.htm=com.ohouse.main.handler.MainHandler
/search.htm=com.ohouse.search.handler.SearchHandler
/shopping.htm=com.ohouse.shopping.handler.shoppingHomeHandler

/signup.htm=com.ohouse.member.handler.SignupHandler
/login.htm=com.ohouse.member.handler.LoginHandler
/logout.htm=com.ohouse.member.handler.LogoutHandler
/changePwd.htm=com.ohouse.member.handler.PasswordChangeFormHandler
/changePwdPro.htm=com.ohouse.member.handler.ChangePwdProHandler
/member/myPage.htm=com.ohouse.member.handler.MyPageHandler

/seller/addForm.htm=com.ohouse.seller.handler.ProductAddHandler
/seller/addPro.htm=com.ohouse.seller.handler.ProductAddProHandler
/seller/deletePro.htm=com.ohouse.seller.handler.ProductDeleteHandler
/seller/editForm.htm=com.ohouse.seller.handler.ProductEditFormHandler
/seller/editPro.htm=com.ohouse.seller.handler.ProductEditProHandler
/seller/dashboard.htm=com.ohouse.seller.handler.SellerDashboardHandler
/seller/productList.htm=com.ohouse.seller.handler.SellerProductListHandler
/seller/signup.htm=com.ohouse.seller.handler.SellerSignupHandler
/seller/login.htm=com.ohouse.seller.handler.SellerLoginHandler
/seller/sellerSignupStatus.htm=com.ohouse.seller.handler.SellerSignupStatusHandler

/admin/memberList.htm=com.ohouse.admin.handler.AllMemberListHandler
/admin/deleteMember.htm=com.ohouse.admin.handler.MemberDeleteHandler
/admin/sellerList.htm=com.ohouse.admin.handler.SellerListHandler
/admin/pendingSellers.htm=com.ohouse.admin.handler.PendingSellerListHandler
/admin/approveSeller.htm=com.ohouse.admin.handler.SellerApprovalHandler
/admin/deleteSeller.htm=com.ohouse.admin.handler.SellerDeleteHandler
/admin/productList.htm=com.ohouse.admin.handler.AdminProductListHandler
/admin/dashboard.htm=com.ohouse.admin.handler.AdminDashboardHandler
/admin/deleteProduct.htm=com.ohouse.admin.handler.AdminProductDeleteHandler

/productDetail.htm=com.ohouse.product.productDetail.handler.ProductDetailHandler
/productOption.htm=com.ohouse.product.productDetail.handler.ProductOptionHandler
/couponlist.htm=com.ohouse.shopping.handler.CouponHandler

/cartAdd.htm=com.ohouse.product.cart.handler.CartAddHandler
/cart.htm=com.ohouse.product.cart.handler.CartListHandler
/cartOptionEdit.htm=com.ohouse.product.cart.handler.CartOptionEditHandler
/cartQuantityEdit.htm=com.ohouse.product.cart.handler.CartQuantityEditHandler
/cartDelete.htm=com.ohouse.product.cart.handler.CartDeleteHandler
/cartOrder.htm=com.ohouse.product.cart.handler.CartOrderHandler

/productOrder.htm=com.ohouse.product.order.handler.ProductOrderHandler
/order.htm=com.ohouse.product.order.handler.OrderHandler

/shopping/category/category.htm=com.ohouse.shopping.category.handler.CategoryHandler

/review.htm=com.ohouse.product.review.handler.ReviewListHandler
/helpCountToggle.htm=com.ohouse.product.review.handler.HelpCountToggleHandler
/hideImageToggle.htm=com.ohouse.product.review.handler.HideImageToggleHandler
/adminReply.htm = com.ohouse.product.review.handler.AdminReplyHandler
/writeReview.htm =com.ohouse.product.review.handler.WriteReviewHandler