REM INSERTING into OHOUSE.MEMBER_COUPON
SET DEFINE OFF;
Insert into OHOUSE.MEMBER_COUPON (MEMBER_COUPON_ID,MEMBER_ID,COUPON_ID,ISSUED_DATE,USED_DATE,STATUS) values (1,3,1,to_date('26/08/25','RR/MM/DD'),null,'AVAILABLE');
Insert into OHOUSE.MEMBER_COUPON (MEMBER_COUPON_ID,MEMBER_ID,COUPON_ID,ISSUED_DATE,USED_DATE,STATUS) values (2,3,2,to_date('26/08/22','RR/MM/DD'),null,'EXPIRED');
