REM INSERTING into OHOUSE.MEMBER
SET DEFINE OFF;
Insert into OHOUSE.MEMBER (MEMBER_ID,ID,NAME,PASSWORD,REG_DATE,RANK,ROLE) values (2,'asd','asd2','1234',to_date('26/08/22','RR/MM/DD'),'NORMAL',null);
Insert into OHOUSE.MEMBER (MEMBER_ID,ID,NAME,PASSWORD,REG_DATE,RANK,ROLE) values (3,'admin','관리자','1234',to_date('26/08/22','RR/MM/DD'),'NORMAL','ADMIN');
Insert into OHOUSE.MEMBER (MEMBER_ID,ID,NAME,PASSWORD,REG_DATE,RANK,ROLE) values (22,'hmpro1021','류호훈','rr112645',to_date('26/08/24','RR/MM/DD'),'NORMAL','USER');
