/main.htm=com.ohouse.main.handler.MainHandler
/shopping/category/category.htm=com.ohouse.shopping.category.handler.CategoryHandler
/shopping/product/productDetail.htm=com.ohouse.product.productDetail.handler.ProductDetailHandler
/shopping/product/productOption.htm=com.ohouse.product.productDetail.handler.ProductOptionHandler